all : LinerTime ViolateMaxSub
LinerTime:
	g++ -o LinerTime -g -Wall LinerTimeMaxSubArray/LinerTimeMaxSubArray.cpp
ViolateMaxSub:
	g++ -o ViolateMaxSub -g -Wall ViolateMaxSubArray/ViolateMaxSubArray.cpp
clean:
	rm -rf LinerTime ViolateMaxSub *.dSYM
